baseURL = "https://wiki.v-os.dev/"
title = "VitruvianOS Wiki"
theme = "hugo-book"
defaultContentLanguage = "en"

[params]
  BookTheme = "light"
  BookSearch = true
  BookRepo = "https://github.com/VitruvianOS/Vitruvian"
  BookToC = true
  BookMenuBundle = false
  BookEditPath = "wiki"

[[menu.before]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/VitruvianOS/Vitruvian"
  weight = 1
